# Generated by Django 6.0 on 2025-12-09 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PRIN', 'Árbitro Principal'), ('ASIS', 'Árbitro Asistente'), ('CUAR', 'Cuarto Árbitro'), ('VAR', 'Árbitro VAR')], default='PRIN', max_length=4)),
                ('experiencia_años', models.PositiveIntegerField(default=0)),
                ('federacion', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='arbitros/')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('fundacion', models.DateField()),
                ('colores', models.CharField(max_length=100)),
                ('presidente', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='equipos/')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=100)),
                ('licencia', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio_contrato', models.DateField()),
                ('fecha_fin_contrato', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='entrenadores/')),
                ('equipo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_tecnico', to='app_Futbol.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('año_inauguracion', models.PositiveIntegerField()),
                ('direccion', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='estadios/')),
                ('equipo_local', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sede_oficial', to='app_Futbol.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=100)),
                ('posicion', models.CharField(choices=[('POR', 'Portero'), ('DEF', 'Defensa'), ('MED', 'Mediocampista'), ('DEL', 'Delantero')], max_length=3)),
                ('numero_camiseta', models.PositiveIntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jugadores/')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='app_Futbol.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('goles_local', models.PositiveIntegerField(default=0)),
                ('goles_visitante', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('JUG', 'Jugándose'), ('FIN', 'Finalizado'), ('SUS', 'Suspendido')], default='PEN', max_length=3)),
                ('asistencia', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='partidos/')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='app_Futbol.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='app_Futbol.equipo')),
                ('estadio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos', to='app_Futbol.estadio')),
            ],
        ),
    ]
